### ISSUE TITLE
about the caffe layer 'split'

### ISSUE THREAD

**Issue by LuyueBUPT** [Zheng222/IDN-Caffe#1]
I can't figure out why the code use split layer. why could't connect the above layer directly like Resnet?
Hoping for your response.

**Comment by Zheng222** [comment]
Hello, the purpose of using the split layer is to make the network more clear, of course, without split is also ok, caffe will automatically add the split operation when generating the network. @LuyueBUPT

**Comment by LuyueBUPT** [comment]
I get it. Thank you !
