### ISSUE TITLE
Does this model supports opencv dnn inference module? 

### ISSUE THREAD

**Issue by ghimiredhikura** [Zheng222/IDN-Caffe#11]
Thank you @Zheng222 for this wonderful work. 

I am trying to use opencv dnn inference module for your SR method. 
I will be grateful if you can explain these lines of code in your `IDN-Caffe/test/test_IDN.m` file. 

```ruby
   im_input=permute(im_l,[2,1,3]);
    net.blobs('data').reshape([size(im_input),1,1]);
    net.reshape();
    net.blobs('data').set_data(im_input); 
    net.forward_prefilled();
    im_result=net.blobs('upsample').get_data();
    
    im_h=im_result'+mycrop(im_b,up_scale);
    time_idn(i)=toc;
```

Best,
Deepak

**Comment by Zheng222** [comment]
@ghimiredhikura Hello, the above code segment indicates that preparing the input image first and then sent it to the network. It is a basic operation in MatCaffe, I recommend you learn the official guidance of [matcaffe](http://caffe.berkeleyvision.org/tutorial/interfaces.html).  If you are familiar with pytorch, you can reference [a third party implementation of IDN](https://github.com/lizhengwei1992/IDN-pytorch).

**Comment by ghimiredhikura** [comment]
Thank you @Zheng222 . Actually I successfully reproduce results in using opencv dnn.
