### ISSUE TITLE
IFC测试的细节

### ISSUE THREAD

**Issue by qiuyajun** [Zheng222/IDN-Caffe#13]
您好,我对您的实验十分感兴趣,您能向我详细描述下IFC测试的细节吗,比如测试时需要对图片做什么样的操作,再放进ifcvec这个函数中,我试过很多种处理,算出的值都不正常,希望您能帮忙下,十分感激.

**Comment by Zheng222** [comment]
@qiuyajun ，https://github.com/Zheng222/IDN-Caffe/blob/2ad2b6d98c0751353c7a69fe9fc5c473a07faf2b/test/test_IDN.m#L97-L100
这里的im_gnd和im_h的数据类型是uint8，数据范围是[0, 255]，只要加上double()函数再送进ifcvec函数就可以了。

**Comment by qiuyajun** [comment]
好的  谢谢啦
