### ISSUE TITLE
网络过程理解

### ISSUE THREAD

**Issue by Tomhouxin** [Zheng222/IDN-Caffe#16]
您好，我没有跑caffe的代码，因为没有matlab环境并且对matlab不熟悉，但我试了下TF的代码，速度还可以，但还想进一步优化，现在想把caffe的模型先迁移到ncnn。
问题：网络过程的理解不知是否正确？理解不对的还望指正
 输入的是低分辨图和双三次插值图的两个Y分量，经过隐藏层后，最后通过输出名“upsample”得到的结果就是超分辩后的图，也是Y分量，最终再将UV分量加上成为彩图？

**Comment by Tomhouxin** [comment]
![image](https://user-images.githubusercontent.com/23637856/57283175-214a9800-70e1-11e9-83fa-dfcfea60c869.png)
就是整个网络执行的是黑线框还是红线框？

**Comment by Zheng222** [comment]
@Tomhouxin 你好，tensorflow版本的输入和输出直接是RGB图像，且输出的尺寸刚好是期望放大到的尺寸。至于caffe版本的话，输入图是Y通道的，输出的残差图也是Y通道的，bicubic这个也是Y通道的，最后再concatenate 经过bicubic放大的Cb和Cr通道。Caffe版本的网络执行的是黑色框的部分，Tensorflow网络执行的是红色框的。

**Comment by Tomhouxin** [comment]
好的，谢谢。
但是现在模型迁移后，我还没改动网络结构，模型输出的结果好像不对，当然我输入的是单通道的灰度图，但是我比较了Y通道和灰度图的值是完全相同的，所以应该不是这个问题导致。如果可以的话能否加我qq：2235665385，允许我进一步请教一下
