### ISSUE TITLE
caffe编译问题

### ISSUE THREAD

**Issue by quankainwafu** [Zheng222/IDN-Caffe#18]
在下新手，第一步里面需要编译.cpp  .hpp  .cu文件，本人caffe框架用的不多，能不能讲讲如何编译呢？caffe环境已搭建，可能就是因为没有编译这几个文件，没法调用新定义的功能，无法训练。感激不尽。

**Comment by Zheng222** [comment]
@quankainwafu 不怎么用caffe的话，可以直接参考我的tensorflow版本的IDN代码实现[https://github.com/Zheng222/IDN-tensorflow](https://github.com/Zheng222/IDN-tensorflow)。至于caffe编译建议你去网上找找资料。
