### ISSUE TITLE
About FLOPs of IDN

### ISSUE THREAD

**Issue by SanSLee** [Zheng222/IDN-Caffe#19]
Hello! Thanks for providing the model size. I want to ask the computational complexity of IDN for scale x2, x3, x4 respectively， which is measured by FLOPs.  Looking forward to your reply.

**Comment by Zheng222** [comment]
@UESTCshiny 

Hello, please calculate the FLOPs manually or you can implement IDN with Pytorch and compute the FLOPs automatically by [thop](https://github.com/Lyken17/pytorch-OpCounter).
