### ISSUE TITLE
resize my pic with this model 

### ISSUE THREAD

**Issue by BUAA-21Li** [Zheng222/IDN-Caffe#4]
Hi,Thank you for your attention. I want to Resize a picture with your trained model.  In your Test_IDN.m file,a picture should be split Y,cb and cr 3 channels,then only Y channel is processed by network,and merged with cb,cr.QUESTION is if I process Y channel of image and enlarge 3 times.what should I do with other two channels? Shoule I use another method to enlarge CB and CR channels and merge them?

**Comment by Zheng222** [comment]
Hello, the general method of upscaling Cb and Cr channels is **bicubic**. This operation has completed in our code. @BUAA-21Li
