### ISSUE TITLE
Result seems strange in paper

### ISSUE THREAD

**Issue by GengDavid** [Zheng222/IDN-Caffe#6]
Hi @Zheng222 
Thanks for your great work.   
But I'm a little confused about the “barbara” result in your paper.   
As we can see that the original image that there are several books "stacked" in the red box 
![ori](https://user-images.githubusercontent.com/16283388/43188986-17611034-9028-11e8-8571-12d6e5808b76.png)

But I found the result you've shown looks like some “diagonal lines”.
![res](https://user-images.githubusercontent.com/16283388/43188943-febfbf80-9027-11e8-9d75-c34d870da58b.png)

It is a little strange since I've tried to use even "Bicubic" method(with an upscaling factor 4), no “diagonal lines” occurs in my experiments. Wonder that why the results shown in your paper look like that? Am I missing something?
Thx!

**Comment by Zheng222** [comment]
Hello, you can see the result from RCAN (ECCV'18) `https://github.com/yulunzhang/RCAN/blob/master/Figs/supp_fig1_visual_compare_gan_psnr_ssim_bi_x4_1.PNG`. From this picture, we can also see that there are diagonal artifacts in the images generated by many methods. @GengDavid

**Comment by GengDavid** [comment]
@Zheng222 Thanks for your reply.
Well, maybe I found what my problem is. I used a high resolution image as input, so the upsampling result would be much better.

**Comment by GengDavid** [comment]
I got the similar result. Thanks!
I'll close this issue.
