### ISSUE TITLE
The sum at the end of a enhancement block 

### ISSUE THREAD

**Issue by cao-nv** [Zheng222/IDN-Caffe#7]
Could you explain the that 'sum' operator at the end of each enhancement block? 
I'm attempting to reproduce your network in Tensorflow, and I got an issue with that 'sum' operator. 
How does the operator work with two inputs of different channel numbers (concatenated input and output of P1, output of P2) ?

**Comment by Zheng222** [comment]
Hello, @cao-nv , please refer to below figure that depicts the details of enhancement unit.
<p align="center">
  <img src="https://raw.githubusercontent.com/Zheng222/IDN-Caffe/master/files/enhancement_unit.png" width=300>
</p>
The sum operator is just element-wise summation.

**Comment by cao-nv** [comment]
Thanks for your reply! So `s` has to be determined to satisfy `D3` and `d`

**Comment by Zheng222** [comment]
@cao-nv Sepcifically, 's' in the paper is set to 4，so the split operator (orange circle) divides preceding features into two parts. One is 16 channels (1/4 * 64), another is 48 (3/4 * 64).
