### ISSUE TITLE
修改损失函数，重新编译出现了错误

### ISSUE THREAD

**Issue by yuankunpeng** [Zheng222/IDN-Caffe#8]
你好，我在修改完损失函数后，重新编译时遇到了错误，你能帮我看一下吗？谢谢！
Makefile:488: target '.build_release/.lint/src/caffe/layers/l1_loss_layer.lint.txt' given more than once in the same rule
Makefile:554: target '.build_release/src/caffe/layers/l1_loss_layer' doesn't match the target pattern
Makefile:554: target '.build_release/cuda/src/caffe/layers/l1_loss_layer' doesn't match the target pattern
CXX src/caffe/solvers/adam_solver.cpp
In file included from ./include/caffe/sgd_solvers.hpp:7:0,
                 from src/caffe/solvers/adam_solver.cpp:3:
./include/caffe/solver.hpp:3:30: fatal error: boost/function.hpp: 没有那个文件或目录
compilation terminated.
Makefile:581: recipe for target '.build_release/src/caffe/solvers/adam_solver.o' failed
make: *** [.build_release/src/caffe/solvers/adam_solver.o] Error 1

**Comment by Zheng222** [comment]
@yuankunpeng Hello, I have sent you a email to explain this problem, thank you.
