### ISSUE TITLE
为什么train  比test 多了一个残差层？

### ISSUE THREAD

**Issue by zkeenly** [Zheng222/IDN-Caffe#9]
<img width="169" alt="image" src="https://user-images.githubusercontent.com/6647857/47985784-c75b1c80-e115-11e8-9150-fe1ba8100ac0.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/6647857/47985791-ccb86700-e115-11e8-810f-4321f2a49052.png">
在最后计算loss的时候，train 的网络里面有一个sum层，而test 却没有sum层。

**Comment by zkeenly** [comment]
另外，train 里面，upsample 之后，特征图会变大X倍，如何进行sum将data与残差相加？

**Comment by zkeenly** [comment]
训练的时候有一个bic 输入，这个是data输入的X倍大小。测试的时候却没有bic。训练计算loss 是sum与lable 计算的，而test 直接将upsample作为输出?

**Comment by Zheng222** [comment]
@zkeenly 你好，在测试阶段双三次插值放大这个操作是直接在matlab中进行的。详细代码请看`test/test_IDN.m` 中的
```    im_input=permute(im_l,[2,1,3]);
    net.blobs('data').reshape([size(im_input),1,1]);
    net.reshape();
    net.blobs('data').set_data(im_input); 
    net.forward_prefilled();
    im_result=net.blobs('upsample').get_data();
    
    im_h=im_result'+mycrop(im_b,up_scale);
```

这里的im_b是对低分辨率图双三次插值之后的结果，mycrop函数则进行裁边以匹配由于反卷积造成的尺寸变化。
